version: '3.8'

services:

  kanban-postgres:
    image: postgres:latest
    container_name: kanban-postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    ports:
      - "5432:5432"
    networks:
      - kanban-net

  kanban-app:
    image: ghcr.io/${GHCR_USERNAME}/kanban-app:latest
    container_name: kanban-app
    depends_on:
      - kanban-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://kanban-postgres:5432/kanban
      SPRING_DATASOURCE_USERNAME: kanban
      SPRING_DATASOURCE_PASSWORD: kanban
    networks:
      - kanban-net

  kanban-frontend:
    image: ghcr.io/${GHCR_USERNAME}/kanban-frontend:latest

    container_name: kanban-frontend
    depends_on:
      - kanban-app
    networks:
      - kanban-net

  nginx:
    image: nginx:latest
    container_name: kanban-nginx
    ports:
      - "8000:80"
      - "44300:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/selfsigned.crt:/etc/nginx/certs/selfsigned.crt:ro
      - ./nginx/certs/selfsigned.key:/etc/nginx/certs/selfsigned.key:ro
    depends_on:
      - kanban-frontend
      - kanban-app
    networks:
      - kanban-net

  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_wal:/wal
      - loki_chunks:/loki/chunks
      - loki_index:/loki/index
    networks:
      - kanban-net

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - kanban-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kanban-net

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    networks:
      - kanban-net

networks:
  kanban-net:
    driver: bridge

volumes:
  loki_wal:
  loki_chunks:
  loki_index:
