name: CI/CD Pipeline

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build backend image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/kanban-app:latest ./task8/kanban-backend

      - name: Build frontend image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/kanban-frontend:latest ./task8/kanban-frontend

      - name: Push images to GHCR
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/kanban-app:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/kanban-frontend:latest

      - name: Setup environment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "GHCR_USERNAME=${{ secrets.GHCR_USERNAME }}" > /opt/armvi-kanban/.env
            cd /opt
            rm -rf armvi-kanban
            mkdir -p armvi-kanban
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Copy configs to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'task8'
          target: '/opt/armvi-kanban'
          strip_components: 1

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/armvi-kanban
            docker-compose down
            docker-compose pull
            docker-compose up -d
      
      - name: Finality
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker logout ghcr.io

